# REST CLIENT VSCODE to test api endPoints
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "email": "test1@gmail.com",
    "password": "1Anc!23123"
}

###
# Gran Token After POST request and put Bearer <TOKEN>
###
GET http://localhost:3001/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlkIjoiNjYzMDUyMDgxMTI3OGIyYzgzMTY5MTYwIiwiaWF0IjoxNzE0NDQyNzczLCJleHAiOjE3MTQ0NDYzNzN9.-ghFlydgy78Gf4w_9IEUhdmUbEDYkMgubFFTNBjeNow

###

POST http://localhost:3001/api/register HTTP/1.1
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "1Anc!23123"
}

###

GET http://localhost:3001/api/register HTTP/1.1


