# REST CLIENT VSCODE to test api endPoints
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "email": "1111111@gmail.com",
    "password": "1Anc!23123"
}

###
# Gran Token After POST request and put Bearer <TOKEN>
###
GET http://localhost:3001/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjExMTExMTFAZ21haWwuY29tIiwiaWQiOiI2NjRiMTZhNDgwNDAyY2E2NjgyZWM2NzEiLCJpYXQiOjE3MTYxOTgwOTYsImV4cCI6MTcxNjIwMTY5Nn0.FrZiIUyYaPAaqfdX4qKiGuMh4obR1HhPMwxh4xihsuY

###

POST http://localhost:3001/api/register HTTP/1.1
Content-Type: application/json

{
    "email": "11111231111@gmail.com",
    "password": "1Anc!23123",
    "firstName": "Vinson",
    "lastName": "----"
}

###

GET http://localhost:3001/api/register HTTP/1.1


